from enum import Enum


class IncidentStatus(str, Enum):
    DETECTED = "DETECTED"
    CORRELATING = "CORRELATING"
    DIAGNOSING = "DIAGNOSING"
    DIAGNOSED = "DIAGNOSED"
    ACTION_PROPOSED = "ACTION_PROPOSED"
    AWAITING_APPROVAL = "AWAITING_APPROVAL"
    EXECUTING = "EXECUTING"
    VALIDATING = "VALIDATING"
    RESOLVED = "RESOLVED"
    FAILED_REMEDIATION = "FAILED_REMEDIATION"
    ESCALATED = "ESCALATED"